#include "tcPythonBind.h"

#include "tcFlightPortInterface.h"
#include "tcPlatformInterface.h"
using namespace scriptinterface;
void BindFlightPort(module &m)
{
    py::class_<tcFlightUnitStatus>(m, "FlightUnitStatus")
    .def_readonly("name", &tcFlightUnitStatus::unit_name)
        .def_readonly("current_loc", &tcFlightUnitStatus::current_loc)
        .def_readonly("goal_loc", &tcFlightUnitStatus::goal_loc)
        .def_readonly("atDestination", &tcFlightUnitStatus::atDestination)
        .def_readonly("isIdle", &tcFlightUnitStatus::isIdle)
        .def_readonly("runway", &tcFlightUnitStatus::runway)
        .def_readonly("ready_time", &tcFlightUnitStatus::ready_time);

    py::class_<tcFlightPortInterface>(m,"FlightPortInterface")
        .def(py::init<>())
        .def("GetCurrentTime",&tcFlightPortInterface::GetTime)
        .def("GetUnitCount", &tcFlightPortInterface::GetUnitCount)
        .def("GetUnitID", &tcFlightPortInterface::GetUnitID)
        .def("GetUnitName", &tcFlightPortInterface::GetUnitName)
        .def("GetUnitStatus", &tcFlightPortInterface::GetUnitStatus)
        .def("GetUnitLocation", &tcFlightPortInterface::GetUnitLocation)
        .def("GetUnitGoalLocation", &tcFlightPortInterface::GetUnitGoalLocation)
        .def("GetUnitPlatformInterface", &tcFlightPortInterface::GetUnitPlatformInterface)
        .def("IsValid", &tcFlightPortInterface::IsValid)
        .def("Launch", &tcFlightPortInterface::Launch)
        .def("LaunchID", &tcFlightPortInterface::LaunchID)
        .def("SetDestination", &tcFlightPortInterface::SetDestination)
        .def("GetLocalObj",&tcFlightPortInterface::GetLocalObj)
        // mission related commands
        .def("AddGenericMission", &tcFlightPortInterface::AddGenericMission)
        .def("AddAircraftToMission", &tcFlightPortInterface::AddAircraftToMission)
        .def("AddCAPMission", &tcFlightPortInterface::AddCAPMission)
        .def("AddAEWMission", &tcFlightPortInterface::AddAEWMission)
        .def("AddASWMission", &tcFlightPortInterface::AddASWMission)
        .def("AddAttackMission", &tcFlightPortInterface::AddAttackMission)
        .def("GetMissionCount", &tcFlightPortInterface::GetMissionCount)
        .def("GetMissionId", &tcFlightPortInterface::GetMissionId)
        .def("GetEditMissionId", &tcFlightPortInterface::GetEditMissionId)
        .def("SetEditMissionId", &tcFlightPortInterface::SetEditMissionId)
        .def("AddMissionWaypoint", &tcFlightPortInterface::AddMissionWaypoint)
        .def("AddMissionWaypointAdvanced", &tcFlightPortInterface::AddMissionWaypointAdvanced)
        .def("EditMissionWaypoint", &tcFlightPortInterface::EditMissionWaypoint)
        .def("EditMissionWaypointAdvanced", &tcFlightPortInterface::EditMissionWaypointAdvanced)
        .def("EditMissionWaypointReference", &tcFlightPortInterface::EditMissionWaypointReference)
        .def("GetMissionWaypointCount", &tcFlightPortInterface::GetMissionWaypointCount)
        .def("InsertMissionWaypoint", &tcFlightPortInterface::InsertMissionWaypoint)
        .def("ClearMissionWaypoints", &tcFlightPortInterface::ClearMissionWaypoints)
        .def("DeleteMissionWaypoint", &tcFlightPortInterface::DeleteMissionWaypoint)
        .def("SetMissionWaypointTasks", &tcFlightPortInterface::SetMissionWaypointTasks)
        .def("AddMissionWaypointTask", &tcFlightPortInterface::AddMissionWaypointTask)
        .def("RemoveMissionWaypointTask", &tcFlightPortInterface::RemoveMissionWaypointTask)
        .def("SetMissionDatum", &tcFlightPortInterface::SetMissionDatum)
        .def("SetMissionLandingTarget", &tcFlightPortInterface::SetMissionLandingTarget)
        .def("SetMissionLaunchTime", &tcFlightPortInterface::SetMissionLaunchTime)
        .def("SetMissionPatrolArea", &tcFlightPortInterface::SetMissionPatrolArea)
        .def("GetMissionPatrolArea", &tcFlightPortInterface::GetMissionPatrolArea)
        .def("SetMissionPatrolAnchor", &tcFlightPortInterface::SetMissionPatrolAnchor)
        .def("SetMissionType", &tcFlightPortInterface::SetMissionType)
        .def("GetMissionType", &tcFlightPortInterface::GetMissionType)
        .def("TransformToRelativePatrolArea", &tcFlightPortInterface::TransformToRelativePatrolArea)
        .def("TransformToAbsolutePatrolArea", &tcFlightPortInterface::TransformToAbsolutePatrolArea)
        .def("SetMissionWaveQuantity", &tcFlightPortInterface::SetMissionWaveQuantity)
        .def("HasAircraftForMission", &tcFlightPortInterface::HasAircraftForMission)
        ;
}
